/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import controller.ProjectController;
import model.Project;


public class App {
    

    public static void main(String[] args) {
        
        
    }
        
}
